crud/urls.py
from django.urls import path

from . import views

app_name = 'crud'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('adduser/', views.addUser, name='adduser'),
    #id hash
    #path(r'^(?P<id>\d)/$', views.deleteUser, name='deleteuser'),
    path('<int:user_id>/delete/', views.deleteUser, name='deleteuser'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='updateview'),
    path('<int:user_id>/updateproccess/', views.updateUser, name='updateuser'),
    path('product/', views.ProductView.as_view(), name='index_product'),
    path('addproduct/', views.addProduct, name='addproduct'),
    path('<int:product_id>/deleteproduct/', views.deleteProduct, name='deleteproduct'),
    path('<int:pk>/product/update/', views.UpdateView_product.as_view(), name='updateviewproduct'),
    path('<int:product_id>/updateproccessproduct/', views.updateProduct, name='updateproduct'),
]
#pip install mysql
#python manage.py makemigrations
#python manage.py migrate
#python manage.py createsuperuser
#python manage.py runserver

crudpythondjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('crud/', include('crud.urls')),
    path('admin/', admin.site.urls),
]

crud/models.py
from django.db import models

# Create your models here.

# 
class User(models.Model):
    # 
    username = models.CharField(max_length=10)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    # kita ingin model menampilkan username(default: User object (1))
    def __str__(self):
        return self.username


class Product(models.Model):
    # 
    product_name = models.CharField(max_length=30)
    # kita ingin model menampilkan username(default: User object (1))
    def __str__(self):
        return self.username

# 

crud/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from crud.models import User
from crud.models import Product
from django.urls import reverse

from django.shortcuts import get_object_or_404, render


# generic views
class IndexView(generic.ListView):

    template_name = "crud/index.html"
    
    context_object_name = 'users'

    def get_queryset(self):
        """blabla"""
        return User.objects.all()

# 
def addUser(request):
    # jika field form ada yang kosong
    if len(request.POST['username']) == 0 or len(request.POST['first_name']) == 0 or len(request.POST['last_name']) == 0 :
        users = User.objects.all()
        # hanya redierect ke index
        return HttpResponseRedirect(reverse('crud:index'))
    else:
        # insert ke database
        new_user = User.objects.create(username=request.POST['username'].lower(), first_name=request.POST['first_name'].title(), last_name=request.POST['last_name'].title())
        # execute
        new_user.save()
        # redirect ke halaman index
        return HttpResponseRedirect(reverse('crud:index'))

# 
def deleteUser(request, user_id):
    user_delete = User.objects.get(id=user_id)
    user_delete.delete()
    return HttpResponseRedirect(reverse('crud:index'))

# 
class UpdateView(generic.DetailView):
    model = User
    # 
    template_name = "crud/update.html"
    
    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        # ini adalah context_object_name, context['users']
        context['users'] = User.objects.filter(pk=self.kwargs['pk'])
        return context

# 
def updateUser(request, user_id):
    # update data
    User.objects.filter(id=user_id).update(username=request.POST['username'].lower(), first_name=request.POST['first_name'].title(), last_name=request.POST['last_name'].title())
    # 
    return HttpResponseRedirect(reverse('crud:index'))
# generic views
class ProductView(generic.ListView):

    template_name = "crud/product.html"
    
    context_object_name = 'products'

    def get_queryset(self):
        """blabla"""
        return Product.objects.all()
# 
def addProduct(request):
    # jika field form ada yang kosong
    if len(request.POST['product_name']) == 0 :
        Products = Product.objects.all()
        # hanya redierect ke product
        return HttpResponseRedirect(reverse('crud:index_product'))
    else:
        # insert ke database
        new_product = Product.objects.create(product_name=request.POST['product_name'].lower())
        # execute
        new_product.save()
        # redirect ke halaman product
        return HttpResponseRedirect(reverse('crud:index_product'))

# 
def deleteProduct(request, product_id):
    user_delete = Product.objects.get(id=product_id)
    user_delete.delete()
    return HttpResponseRedirect(reverse('crud:index_product'))

# 
class UpdateView_product(generic.DetailView):
    model = Product
    # 
    template_name = "crud/update_product.html"
    
    def get_context_data(self, **kwargs):
        context = super(UpdateView_product, self).get_context_data(**kwargs)
        # ini adalah context_object_name, context['users']
        context['products'] = Product.objects.filter(pk=self.kwargs['pk'])
        return context

# 
def updateProduct(request, product_id):
    # update data
    Product.objects.filter(id=product_id).update(product_name=request.POST['product_name'].lower())
    # 
    return HttpResponseRedirect(reverse('crud:index_product'))

crud/templates/crud/index.html
{% load static %}
<!-- bootstrap -->
<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}">

<!-- body -->
<div class="container">
    <!-- form -->
    <div class="row mt-3">
        <div class="col-md-4">
            <h2>Tambah User</h2>
            <form action="{% url 'crud:adduser' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" name="first_name" placeholder="First name">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" name="last_name" placeholder="Last name">
                </div>
                <button type="submit" name="btn_add" class="btn btn-primary">Add</button>
            </form>
        </div>
        <!-- table -->
        <div class="col-md-8 text-center">
            <h2 class="mb-3">Daftar User</h2>
            {% if users %}
            <table class="table">
                <tr>
                    <th>No.</th>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Action</th>
                </tr>
                <script>
                    let no = 1;
                </script>
                {% for user in users %}
                <tr>
                    <td><script>document.write(no);</script></td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>
                        <a href="{% url 'crud:deleteuser' user.id %}">Hapus</a>
                        <a href="{% url 'crud:updateview' user.id %}">edit</a>
                    </td>
                </tr>
                <script>
                    no++;
                </script>
                {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>
</div>

crud/templates/crud/product.html
{% load static %}
<!-- bootstrap -->
<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}">

<!-- body -->
<div class="container">
    <div class="row mt-3">
        <a style="border: black 2px solid;padding: 2px 12px 2px 12px;margin-right: 10px;border-radius: 10px;text-decoration: none;}" href="{% url 'crud:index' %}">
            <h2>User</h2>
        </a>
        <a style="border: black 2px solid;padding: 2px 12px 2px 12px;margin-right: 10px;border-radius: 10px;text-decoration: none;}" href="{% url 'crud:index_product' %}">
            <h2>Product</h2>
        </a>
    </div>
    <!-- form -->
    <div class="row mt-3">
        <div class="col-md-4">
            <h2>Tambah Product</h2>
            <form action="{% url 'crud:addproduct' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="product_name" placeholder="Product Name">
                </div>
                <button type="submit" name="btn_add" class="btn btn-primary">Add</button>
            </form>
        </div>
        <!-- table -->
        <div class="col-md-8 text-center">
            <h2 class="mb-3">Daftar Product</h2>
            {% if products %}
            <table class="table">
                <tr>
                    <th>No.</th>
                    <th>Product Name</th>
                </tr>
                <script>
                    let no = 1;
                </script>
                {% for product in products %}
                <tr>
                    <td><script>document.write(no);</script></td>
                    <td>{{ product.product_name }}</td>
                    <td>
                        <a href="{% url 'crud:deleteproduct' product.id %}">Hapus</a>
                        <a href="{% url 'crud:updateviewproduct' product.id %}">edit</a>
                    </td>
                </tr>
                <script>
                    no++;
                </script>
                {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>
</div>

crud/templates/crud/update.html
{% load static %}
<!-- bootstrap -->
<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}">

<!-- body -->
<div class="container">
    <!-- form -->
    <div class="row justify-content-center mt-3">
        <div class="col-md-6">
            <h3 class="mb-3">Edit User</h3>
            {% if users %}
                {% for user in users %}
                <form action="{% url 'crud:updateuser' user.id %}" method="post">{% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" name="username" placeholder="Username" value="{{ user.username }}">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="first_name" placeholder="First name" value="{{ user.first_name }}">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="last_name" placeholder="Last name" value="{{ user.last_name }}">
                    </div>
                    <button type="submit" name="btn_edit" class="btn btn-primary">Update</button>
                </form>
                {% endfor %}
            {% endif %}
            <a href="{% url 'crud:index' %}">back to home.</a>
        </div>
    </div>
</div>

crud/templates/crud/update_product.html
{% load static %}
<!-- bootstrap -->
<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}">

<!-- body -->
<div class="container">
    <!-- form -->
    <div class="row justify-content-center mt-3">
        <div class="col-md-6">
            <h3 class="mb-3">Edit Product</h3>
            {% if products %}
                {% for product in products %}
                <form action="{% url 'crud:updateproduct' product.id %}" method="post">{% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" name="product_name" placeholder="Product Name" value="{{ product.product_name }}">
                    </div>
                    <button type="submit" name="btn_edit" class="btn btn-primary">Update</button>
                </form>
                {% endfor %}
            {% endif %}
            <a href="{% url 'crud:index' %}">back to home.</a>
        </div>
    </div>
</div>